/* Generated By:JavaCC: Do not edit this line. CompiladorAulaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompiladorAulaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INICIOPROGRAMA = 5;
  /** RegularExpression Id. */
  int PONTOVIRGULA = 6;
  /** RegularExpression Id. */
  int VIRGULA = 7;
  /** RegularExpression Id. */
  int ABREBLOCO = 8;
  /** RegularExpression Id. */
  int FIMBLOCO = 9;
  /** RegularExpression Id. */
  int INTEIRO = 10;
  /** RegularExpression Id. */
  int ATRIBUICAO = 11;
  /** RegularExpression Id. */
  int BOOLEANA = 12;
  /** RegularExpression Id. */
  int STRING = 13;
  /** RegularExpression Id. */
  int NUMERO = 14;
  /** RegularExpression Id. */
  int DIGITO = 15;
  /** RegularExpression Id. */
  int IF = 16;
  /** RegularExpression Id. */
  int ELSE = 17;
  /** RegularExpression Id. */
  int FOR = 18;
  /** RegularExpression Id. */
  int TO = 19;
  /** RegularExpression Id. */
  int DO = 20;
  /** RegularExpression Id. */
  int TRUE = 21;
  /** RegularExpression Id. */
  int FALSE = 22;
  /** RegularExpression Id. */
  int ID = 23;
  /** RegularExpression Id. */
  int LETRA = 24;
  /** RegularExpression Id. */
  int PALAVRA = 25;
  /** RegularExpression Id. */
  int MAIOR = 26;
  /** RegularExpression Id. */
  int MENOR = 27;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 28;
  /** RegularExpression Id. */
  int MAIOR_IGUAL = 29;
  /** RegularExpression Id. */
  int DIFERENTE = 30;
  /** RegularExpression Id. */
  int IGUAL = 31;
  /** RegularExpression Id. */
  int AND = 32;
  /** RegularExpression Id. */
  int OR = 33;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"bora dar um piao\"",
    "\";\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\"inteiro\"",
    "\"recebe\"",
    "\"teu cu\"",
    "\"desbaratinar uma ideia\"",
    "<NUMERO>",
    "<DIGITO>",
    "\"se pa\"",
    "\"senao mete um migue\"",
    "\"repete essa porra\"",
    "\"ate\"",
    "\"lanca ai\"",
    "\"true\"",
    "\"false\"",
    "<ID>",
    "<LETRA>",
    "<PALAVRA>",
    "\"eh maior\"",
    "\"eh menor\"",
    "\"eh menor ou igual\"",
    "\"eh maior ou igual\"",
    "\"eh diferente\"",
    "\"eh gemeo\"",
    "\"&&\"",
    "\"||\"",
  };

}
